// Maps LeetCode problem URL → GFG problem URL.
// Used in seed.ts to populate gfgUrl across all sheets.
// GFG URL format: https://www.geeksforgeeks.org/problems/[slug]/1
export const GFG_URL_MAP: Record<string, string> = {
  // ── Arrays ────────────────────────────────────────────────────────────────
  "https://leetcode.com/problems/two-sum/":
    "https://www.geeksforgeeks.org/problems/key-pair5616/1",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/":
    "https://www.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/":
    "https://www.geeksforgeeks.org/problems/stock-buy-and-sell2615/1",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/":
    "https://www.geeksforgeeks.org/problems/buy-and-sell-a-stock/1",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/":
    "https://www.geeksforgeeks.org/problems/buy-and-sell-stocks-with-k-transactions/1",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/":
    "https://www.geeksforgeeks.org/problems/buy-and-sell-stocks-with-cooldown/1",
  "https://leetcode.com/problems/contains-duplicate/":
    "https://www.geeksforgeeks.org/problems/who-will-win-1587115621/1",
  "https://leetcode.com/problems/product-of-array-except-self/":
    "https://www.geeksforgeeks.org/problems/product-array-puzzle4525/1",
  "https://leetcode.com/problems/maximum-subarray/":
    "https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1",
  "https://leetcode.com/problems/maximum-product-subarray/":
    "https://www.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  "https://leetcode.com/problems/set-matrix-zeroes/":
    "https://www.geeksforgeeks.org/problems/boolean-matrix-problem-1587115620/1",
  "https://leetcode.com/problems/spiral-matrix/":
    "https://www.geeksforgeeks.org/problems/spirally-traversing-a-matrix-1587115621/1",
  "https://leetcode.com/problems/rotate-image/":
    "https://www.geeksforgeeks.org/problems/rotate-by-90-degree-1587115621/1",
  "https://leetcode.com/problems/sort-colors/":
    "https://www.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1",
  "https://leetcode.com/problems/next-permutation/":
    "https://www.geeksforgeeks.org/problems/next-permutation5226/1",
  "https://leetcode.com/problems/subarray-sum-equals-k/":
    "https://www.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1",
  "https://leetcode.com/problems/rotate-array/":
    "https://www.geeksforgeeks.org/problems/rotate-array-by-n-elements-1587115621/1",
  "https://leetcode.com/problems/move-zeroes/":
    "https://www.geeksforgeeks.org/problems/move-all-zeroes-to-end-of-array0751/1",
  "https://leetcode.com/problems/plus-one/":
    "https://www.geeksforgeeks.org/problems/vector-of-vectors2234/1",
  "https://leetcode.com/problems/valid-sudoku/":
    "https://www.geeksforgeeks.org/problems/check-if-sudoku-is-valid-1587115620/1",
  "https://leetcode.com/problems/find-all-duplicates-in-an-array/":
    "https://www.geeksforgeeks.org/problems/find-duplicates-in-an-array/1",
  "https://leetcode.com/problems/first-missing-positive/":
    "https://www.geeksforgeeks.org/problems/smallest-positive-missing-number-1587115621/1",

  // ── Binary Search ─────────────────────────────────────────────────────────
  "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/":
    "https://www.geeksforgeeks.org/problems/minimum-element-in-a-sorted-and-rotated-array3611/1",
  "https://leetcode.com/problems/search-in-rotated-sorted-array/":
    "https://www.geeksforgeeks.org/problems/search-in-a-rotated-array4618/1",
  "https://leetcode.com/problems/binary-search/":
    "https://www.geeksforgeeks.org/problems/binary-search-1587115620/1",
  "https://leetcode.com/problems/search-insert-position/":
    "https://www.geeksforgeeks.org/problems/search-insert-position-of-k-in-a-sorted-array/1",
  "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/":
    "https://www.geeksforgeeks.org/problems/first-and-last-occurrences-of-x2041/1",
  "https://leetcode.com/problems/find-peak-element/":
    "https://www.geeksforgeeks.org/problems/peak-element/1",
  "https://leetcode.com/problems/median-of-two-sorted-arrays/":
    "https://www.geeksforgeeks.org/problems/median-of-2-sorted-arrays-of-different-sizes-1587115620/1",
  "https://leetcode.com/problems/koko-eating-bananas/":
    "https://www.geeksforgeeks.org/problems/koko-eating-bananas/1",
  "https://leetcode.com/problems/time-based-key-value-store/":
    "https://www.geeksforgeeks.org/problems/time-based-key-value-store/1",
  "https://leetcode.com/problems/search-a-2d-matrix/":
    "https://www.geeksforgeeks.org/problems/search-in-a-matrix-1587115621/1",
  "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/":
    "https://www.geeksforgeeks.org/problems/capacity-to-ship-packages-within-d-days/1",
  "https://leetcode.com/problems/find-k-closest-elements/":
    "https://www.geeksforgeeks.org/problems/find-k-closest-elements/1",

  // ── Sliding Window ────────────────────────────────────────────────────────
  "https://leetcode.com/problems/longest-substring-without-repeating-characters/":
    "https://www.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1",
  "https://leetcode.com/problems/minimum-window-substring/":
    "https://www.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string-1587115621/1",
  "https://leetcode.com/problems/permutation-in-string/":
    "https://www.geeksforgeeks.org/problems/permutation-in-string/1",
  "https://leetcode.com/problems/sliding-window-maximum/":
    "https://www.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k3/1",
  "https://leetcode.com/problems/fruit-into-baskets/":
    "https://www.geeksforgeeks.org/problems/fruit-into-baskets-1587115621/1",
  "https://leetcode.com/problems/count-number-of-nice-subarrays/":
    "https://www.geeksforgeeks.org/problems/count-number-of-nice-subarrays/1",
  "https://leetcode.com/problems/find-all-anagrams-in-a-string/":
    "https://www.geeksforgeeks.org/problems/find-all-anagrams-in-a-string/1",

  // ── Two Pointers ──────────────────────────────────────────────────────────
  "https://leetcode.com/problems/3sum/":
    "https://www.geeksforgeeks.org/problems/triplet-sum-in-array-1587115621/1",
  "https://leetcode.com/problems/container-with-most-water/":
    "https://www.geeksforgeeks.org/problems/container-with-most-water0535/1",
  "https://leetcode.com/problems/valid-palindrome/":
    "https://www.geeksforgeeks.org/problems/palindrome-string0817/1",
  "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/":
    "https://www.geeksforgeeks.org/problems/pair-with-given-sum-in-a-sorted-array4/1",
  "https://leetcode.com/problems/trapping-rain-water/":
    "https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1",
  "https://leetcode.com/problems/3sum-closest/":
    "https://www.geeksforgeeks.org/problems/3-sum-closest1#/1",
  "https://leetcode.com/problems/4sum/":
    "https://www.geeksforgeeks.org/problems/find-all-four-sum-numbers1587115621/1",
  "https://leetcode.com/problems/boats-to-save-people/":
    "https://www.geeksforgeeks.org/problems/boats-to-save-people/1",

  // ── Strings ───────────────────────────────────────────────────────────────
  "https://leetcode.com/problems/valid-anagram/":
    "https://www.geeksforgeeks.org/problems/anagram-1587115620/1",
  "https://leetcode.com/problems/group-anagrams/":
    "https://www.geeksforgeeks.org/problems/print-anagrams-together/1",
  "https://leetcode.com/problems/palindromic-substrings/":
    "https://www.geeksforgeeks.org/problems/count-palindrome-sub-strings-of-a-string0652/1",
  "https://leetcode.com/problems/longest-palindromic-substring/":
    "https://www.geeksforgeeks.org/problems/longest-palindrome-in-a-string3411/1",
  "https://leetcode.com/problems/decode-ways/":
    "https://www.geeksforgeeks.org/problems/total-decoding-messages1235/1",
  "https://leetcode.com/problems/word-break/":
    "https://www.geeksforgeeks.org/problems/word-break1352/1",
  "https://leetcode.com/problems/encode-and-decode-strings/":
    "https://www.geeksforgeeks.org/problems/encode-and-decode-strings/1",
  "https://leetcode.com/problems/longest-common-prefix/":
    "https://www.geeksforgeeks.org/problems/longest-common-prefix-of-all-the-strings-in-an-array/1",
  "https://leetcode.com/problems/is-subsequence/":
    "https://www.geeksforgeeks.org/problems/check-for-subsequence4930/1",
  "https://leetcode.com/problems/reverse-integer/":
    "https://www.geeksforgeeks.org/problems/reverse-digit0/1",
  "https://leetcode.com/problems/count-and-say/":
    "https://www.geeksforgeeks.org/problems/decode-the-pattern/1",
  "https://leetcode.com/problems/happy-number/":
    "https://www.geeksforgeeks.org/problems/happy-number4205/1",

  // ── Stack & Queue ─────────────────────────────────────────────────────────
  "https://leetcode.com/problems/valid-parentheses/":
    "https://www.geeksforgeeks.org/problems/parenthesis-checker2744/1",
  "https://leetcode.com/problems/next-greater-element-i/":
    "https://www.geeksforgeeks.org/problems/next-larger-element-1587115620/1",
  "https://leetcode.com/problems/largest-rectangle-in-histogram/":
    "https://www.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram-1587115620/1",
  "https://leetcode.com/problems/daily-temperatures/":
    "https://www.geeksforgeeks.org/problems/next-greater-element-1587115620/1",
  "https://leetcode.com/problems/car-fleet/":
    "https://www.geeksforgeeks.org/problems/car-fleet/1",
  "https://leetcode.com/problems/evaluate-reverse-polish-notation/":
    "https://www.geeksforgeeks.org/problems/evaluation-of-postfix-expression1735/1",
  "https://leetcode.com/problems/sum-of-subarray-minimums/":
    "https://www.geeksforgeeks.org/problems/sum-of-subarray-minimum/1",
  "https://leetcode.com/problems/generate-parentheses/":
    "https://www.geeksforgeeks.org/problems/generate-all-possible-parentheses/1",
  "https://leetcode.com/problems/implement-queue-using-stacks/":
    "https://www.geeksforgeeks.org/problems/queue-using-two-stacks/1",
  "https://leetcode.com/problems/implement-stack-using-queues/":
    "https://www.geeksforgeeks.org/problems/stack-using-two-queues/1",
  "https://leetcode.com/problems/valid-parenthesis-string/":
    "https://www.geeksforgeeks.org/problems/valid-string5842/1",
  "https://leetcode.com/problems/asteroid-collision/":
    "https://www.geeksforgeeks.org/problems/asteroid-collision/1",
  "https://leetcode.com/problems/decode-string/":
    "https://www.geeksforgeeks.org/problems/decode-the-string2444/1",

  // ── Linked List ───────────────────────────────────────────────────────────
  "https://leetcode.com/problems/reverse-linked-list/":
    "https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1",
  "https://leetcode.com/problems/linked-list-cycle/":
    "https://www.geeksforgeeks.org/problems/detect-loop-in-linked-list/1",
  "https://leetcode.com/problems/merge-two-sorted-lists/":
    "https://www.geeksforgeeks.org/problems/merge-two-sorted-linked-lists/1",
  "https://leetcode.com/problems/merge-k-sorted-lists/":
    "https://www.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1",
  "https://leetcode.com/problems/remove-nth-node-from-end-of-list/":
    "https://www.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1",
  "https://leetcode.com/problems/reorder-list/":
    "https://www.geeksforgeeks.org/problems/reorder-list/1",
  "https://leetcode.com/problems/middle-of-the-linked-list/":
    "https://www.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1",
  "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/":
    "https://www.geeksforgeeks.org/problems/delete-middle-of-linked-list/1",
  "https://leetcode.com/problems/sort-list/":
    "https://www.geeksforgeeks.org/problems/sort-a-linked-list/1",
  "https://leetcode.com/problems/lru-cache/":
    "https://www.geeksforgeeks.org/problems/lru-cache/1",
  "https://leetcode.com/problems/add-two-numbers/":
    "https://www.geeksforgeeks.org/problems/add-two-numbers-1587115620/1",
  "https://leetcode.com/problems/copy-list-with-random-pointer/":
    "https://www.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1",
  "https://leetcode.com/problems/find-the-duplicate-number/":
    "https://www.geeksforgeeks.org/problems/find-duplicate-number/1",
  "https://leetcode.com/problems/reverse-nodes-in-k-group/":
    "https://www.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size1542/1",
  "https://leetcode.com/problems/intersection-of-two-linked-lists/":
    "https://www.geeksforgeeks.org/problems/intersection-point-in-y-shapped-linked-lists/1",
  "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/":
    "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1",
  "https://leetcode.com/problems/lfu-cache/":
    "https://www.geeksforgeeks.org/problems/lfu-cache/1",

  // ── Trees ─────────────────────────────────────────────────────────────────
  "https://leetcode.com/problems/maximum-depth-of-binary-tree/":
    "https://www.geeksforgeeks.org/problems/height-of-binary-tree/1",
  "https://leetcode.com/problems/same-tree/":
    "https://www.geeksforgeeks.org/problems/determine-if-two-trees-are-identical/1",
  "https://leetcode.com/problems/invert-binary-tree/":
    "https://www.geeksforgeeks.org/problems/mirror-tree/1",
  "https://leetcode.com/problems/binary-tree-maximum-path-sum/":
    "https://www.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1",
  "https://leetcode.com/problems/binary-tree-level-order-traversal/":
    "https://www.geeksforgeeks.org/problems/level-order-traversal/1",
  "https://leetcode.com/problems/subtree-of-another-tree/":
    "https://www.geeksforgeeks.org/problems/check-if-subtree/1",
  "https://leetcode.com/problems/validate-binary-search-tree/":
    "https://www.geeksforgeeks.org/problems/check-for-bst/1",
  "https://leetcode.com/problems/kth-smallest-element-in-a-bst/":
    "https://www.geeksforgeeks.org/problems/find-k-th-smallest-element-in-bst/1",
  "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/":
    "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1",
  "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/":
    "https://www.geeksforgeeks.org/problems/construct-tree-1/1",
  "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/":
    "https://www.geeksforgeeks.org/problems/serialize-and-deserialize-a-binary-tree/1",
  "https://leetcode.com/problems/diameter-of-binary-tree/":
    "https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1",
  "https://leetcode.com/problems/balanced-binary-tree/":
    "https://www.geeksforgeeks.org/problems/check-for-balanced-tree/1",
  "https://leetcode.com/problems/binary-tree-right-side-view/":
    "https://www.geeksforgeeks.org/problems/right-view-of-binary-tree/1",
  "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/":
    "https://www.geeksforgeeks.org/problems/flatten-binary-tree-to-linked-list/1",
  "https://leetcode.com/problems/path-sum-ii/":
    "https://www.geeksforgeeks.org/problems/root-to-leaf-paths-sum/1",
  "https://leetcode.com/problems/binary-tree-inorder-traversal/":
    "https://www.geeksforgeeks.org/problems/inorder-traversal/1",
  "https://leetcode.com/problems/count-good-nodes-in-binary-tree/":
    "https://www.geeksforgeeks.org/problems/count-good-nodes-in-binary-tree/1",
  "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/":
    "https://www.geeksforgeeks.org/problems/zigzag-tree-traversal/1",
  "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/":
    "https://www.geeksforgeeks.org/problems/array-to-bst4443/1",
  "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/":
    "https://www.geeksforgeeks.org/problems/nodes-at-distance-k-from-a-given-node/1",
  "https://leetcode.com/problems/find-duplicate-subtrees/":
    "https://www.geeksforgeeks.org/problems/duplicate-subtree-in-binary-tree/1",
  "https://leetcode.com/problems/binary-search-tree-iterator/":
    "https://www.geeksforgeeks.org/problems/inorder-traversal-iterative/1",

  // ── Graphs ────────────────────────────────────────────────────────────────
  "https://leetcode.com/problems/clone-graph/":
    "https://www.geeksforgeeks.org/problems/clone-graph/1",
  "https://leetcode.com/problems/course-schedule/":
    "https://www.geeksforgeeks.org/problems/prerequisite-tasks/1",
  "https://leetcode.com/problems/course-schedule-ii/":
    "https://www.geeksforgeeks.org/problems/topological-sort/1",
  "https://leetcode.com/problems/number-of-islands/":
    "https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1",
  "https://leetcode.com/problems/longest-consecutive-sequence/":
    "https://www.geeksforgeeks.org/problems/longest-consecutive-subsequence2449/1",
  "https://leetcode.com/problems/pacific-atlantic-water-flow/":
    "https://www.geeksforgeeks.org/problems/water-connection-problem5456/1",
  "https://leetcode.com/problems/surrounded-regions/":
    "https://www.geeksforgeeks.org/problems/replace-os-with-xs0052/1",
  "https://leetcode.com/problems/rotting-oranges/":
    "https://www.geeksforgeeks.org/problems/rotten-oranges2536/1",
  "https://leetcode.com/problems/walls-and-gates/":
    "https://www.geeksforgeeks.org/problems/distance-from-guard/1",
  "https://leetcode.com/problems/is-graph-bipartite/":
    "https://www.geeksforgeeks.org/problems/bipartite-graph/1",
  "https://leetcode.com/problems/network-delay-time/":
    "https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1",
  "https://leetcode.com/problems/min-cost-to-connect-all-points/":
    "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1",
  "https://leetcode.com/problems/cheapest-flights-within-k-stops/":
    "https://www.geeksforgeeks.org/problems/cheapest-flights-within-k-stops/1",
  "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/":
    "https://www.geeksforgeeks.org/problems/number-of-provinces/1",
  "https://leetcode.com/problems/graph-valid-tree/":
    "https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1",
  "https://leetcode.com/problems/redundant-connection/":
    "https://www.geeksforgeeks.org/problems/redundant-connection/1",
  "https://leetcode.com/problems/word-ladder/":
    "https://www.geeksforgeeks.org/problems/word-ladder/1",
  "https://leetcode.com/problems/alien-dictionary/":
    "https://www.geeksforgeeks.org/problems/alien-dictionary/1",
  "https://leetcode.com/problems/swim-in-rising-water/":
    "https://www.geeksforgeeks.org/problems/swim-in-rising-water/1",
  "https://leetcode.com/problems/accounts-merge/":
    "https://www.geeksforgeeks.org/problems/accounts-merge/1",
  "https://leetcode.com/problems/01-matrix/":
    "https://www.geeksforgeeks.org/problems/distance-from-nearest-cell-having-1-1587115620/1",
  "https://leetcode.com/problems/find-eventual-safe-states/":
    "https://www.geeksforgeeks.org/problems/eventual-safe-states/1",
  "https://leetcode.com/problems/keys-and-rooms/":
    "https://www.geeksforgeeks.org/problems/keys-and-rooms/1",
  "https://leetcode.com/problems/find-if-path-exists-in-graph/":
    "https://www.geeksforgeeks.org/problems/find-if-path-exists-in-graph/1",
  "https://leetcode.com/problems/evaluate-division/":
    "https://www.geeksforgeeks.org/problems/evaluate-division/1",
  "https://leetcode.com/problems/critical-connections-in-a-network/":
    "https://www.geeksforgeeks.org/problems/bridge-edge-in-graph/1",
  "https://leetcode.com/problems/reconstruct-itinerary/":
    "https://www.geeksforgeeks.org/problems/euler-circuit-in-a-directed-graph/1",
  "https://leetcode.com/problems/number-of-islands-ii/":
    "https://www.geeksforgeeks.org/problems/number-of-islands/1",

  // ── Dynamic Programming ───────────────────────────────────────────────────
  "https://leetcode.com/problems/climbing-stairs/":
    "https://www.geeksforgeeks.org/problems/count-ways-to-reach-the-nth-stair-1587115620/1",
  "https://leetcode.com/problems/coin-change/":
    "https://www.geeksforgeeks.org/problems/coin-change2448/1",
  "https://leetcode.com/problems/coin-change-ii/":
    "https://www.geeksforgeeks.org/problems/count-of-number-of-given-coins0433/1",
  "https://leetcode.com/problems/longest-increasing-subsequence/":
    "https://www.geeksforgeeks.org/problems/longest-increasing-subsequence-1587115620/1",
  "https://leetcode.com/problems/house-robber/":
    "https://www.geeksforgeeks.org/problems/stickler-thief-1587115621/1",
  "https://leetcode.com/problems/house-robber-ii/":
    "https://www.geeksforgeeks.org/problems/house-robber-ii/1",
  "https://leetcode.com/problems/house-robber-iii/":
    "https://www.geeksforgeeks.org/problems/house-robber-ii/1",
  "https://leetcode.com/problems/unique-paths/":
    "https://www.geeksforgeeks.org/problems/number-of-unique-paths5339/1",
  "https://leetcode.com/problems/jump-game/":
    "https://www.geeksforgeeks.org/problems/jump-game/1",
  "https://leetcode.com/problems/jump-game-ii/":
    "https://www.geeksforgeeks.org/problems/minimum-number-of-jumps-1587115620/1",
  "https://leetcode.com/problems/longest-common-subsequence/":
    "https://www.geeksforgeeks.org/problems/longest-common-subsequence-1587115621/1",
  "https://leetcode.com/problems/edit-distance/":
    "https://www.geeksforgeeks.org/problems/edit-distance3702/1",
  "https://leetcode.com/problems/wildcard-matching/":
    "https://www.geeksforgeeks.org/problems/wildcard-string-matching1126/1",
  "https://leetcode.com/problems/regular-expression-matching/":
    "https://www.geeksforgeeks.org/problems/regex-matching-to-wildcard-matching/1",
  "https://leetcode.com/problems/partition-equal-subset-sum/":
    "https://www.geeksforgeeks.org/problems/subset-sum-problem2014/1",
  "https://leetcode.com/problems/target-sum/":
    "https://www.geeksforgeeks.org/problems/target-sum/1",
  "https://leetcode.com/problems/distinct-subsequences/":
    "https://www.geeksforgeeks.org/problems/number-of-distinct-subsequences0909/1",
  "https://leetcode.com/problems/interleaving-string/":
    "https://www.geeksforgeeks.org/problems/interleaving-strings/1",
  "https://leetcode.com/problems/burst-balloons/":
    "https://www.geeksforgeeks.org/problems/burst-balloons/1",
  "https://leetcode.com/problems/longest-palindromic-subsequence/":
    "https://www.geeksforgeeks.org/problems/longest-palindromic-subsequence-1612/1",
  "https://leetcode.com/problems/combination-sum-iv/":
    "https://www.geeksforgeeks.org/problems/perfect-sum-problem5633/1",
  "https://leetcode.com/problems/delete-and-earn/":
    "https://www.geeksforgeeks.org/problems/delete-and-earn/1",
  "https://leetcode.com/problems/largest-divisible-subset/":
    "https://www.geeksforgeeks.org/problems/largest-divisible-subset/1",
  "https://leetcode.com/problems/longest-arithmetic-subsequence/":
    "https://www.geeksforgeeks.org/problems/longest-arithmetic-progression4/1",
  "https://leetcode.com/problems/count-square-submatrices-with-all-ones/":
    "https://www.geeksforgeeks.org/problems/count-number-of-squares-submatrices-with-all-1/1",
  "https://leetcode.com/problems/dungeon-game/":
    "https://www.geeksforgeeks.org/problems/dungeon-game/1",
  "https://leetcode.com/problems/longest-string-chain/":
    "https://www.geeksforgeeks.org/problems/longest-string-chain/1",
  "https://leetcode.com/problems/palindrome-partitioning/":
    "https://www.geeksforgeeks.org/problems/palindrome-patitioning4845/1",

  // ── Heap / Priority Queue ─────────────────────────────────────────────────
  "https://leetcode.com/problems/top-k-frequent-elements/":
    "https://www.geeksforgeeks.org/problems/top-k-frequent-elements-in-array/1",
  "https://leetcode.com/problems/find-median-from-data-stream/":
    "https://www.geeksforgeeks.org/problems/find-median-in-a-stream-1587115621/1",
  "https://leetcode.com/problems/kth-largest-element-in-an-array/":
    "https://www.geeksforgeeks.org/problems/kth-largest-element-in-an-array/1",
  "https://leetcode.com/problems/last-stone-weight/":
    "https://www.geeksforgeeks.org/problems/last-stone-weight/1",
  "https://leetcode.com/problems/k-closest-points-to-origin/":
    "https://www.geeksforgeeks.org/problems/k-closest-point-to-origin/1",
  "https://leetcode.com/problems/task-scheduler/":
    "https://www.geeksforgeeks.org/problems/task-scheduler/1",
  "https://leetcode.com/problems/kth-largest-element-in-a-stream/":
    "https://www.geeksforgeeks.org/problems/kth-largest-element-in-stream-1587115620/1",
  "https://leetcode.com/problems/reorganize-string/":
    "https://www.geeksforgeeks.org/problems/reorganize-string/1",
  "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/":
    "https://www.geeksforgeeks.org/problems/find-k-pairs-with-smallest-sums/1",
  "https://leetcode.com/problems/ipo/":
    "https://www.geeksforgeeks.org/problems/ipo/1",

  // ── Trie ──────────────────────────────────────────────────────────────────
  "https://leetcode.com/problems/implement-trie-prefix-tree/":
    "https://www.geeksforgeeks.org/problems/trie-insert-and-search0651/1",
  "https://leetcode.com/problems/design-add-and-search-words-data-structure/":
    "https://www.geeksforgeeks.org/problems/add-and-search-word-data-structure-design/1",
  "https://leetcode.com/problems/word-search/":
    "https://www.geeksforgeeks.org/problems/word-search/1",
  "https://leetcode.com/problems/word-search-ii/":
    "https://www.geeksforgeeks.org/problems/word-boggle/1",
  "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/":
    "https://www.geeksforgeeks.org/problems/maximum-xor-of-two-numbers-in-an-array/1",

  // ── Backtracking ──────────────────────────────────────────────────────────
  "https://leetcode.com/problems/combination-sum/":
    "https://www.geeksforgeeks.org/problems/combination-sum-part-2/1",
  "https://leetcode.com/problems/combination-sum-ii/":
    "https://www.geeksforgeeks.org/problems/combination-sum-part-2/1",
  "https://leetcode.com/problems/subsets/":
    "https://www.geeksforgeeks.org/problems/subsets1613/1",
  "https://leetcode.com/problems/subsets-ii/":
    "https://www.geeksforgeeks.org/problems/subsets-with-duplicates/1",
  "https://leetcode.com/problems/permutations/":
    "https://www.geeksforgeeks.org/problems/permutations-of-a-given-string0855/1",
  "https://leetcode.com/problems/permutation-sequence/":
    "https://www.geeksforgeeks.org/problems/kth-permutation-sequence/1",
  "https://leetcode.com/problems/letter-combinations-of-a-phone-number/":
    "https://www.geeksforgeeks.org/problems/letter-combinations-of-a-phone-number/1",
  "https://leetcode.com/problems/n-queens/":
    "https://www.geeksforgeeks.org/problems/n-queen-problem0315/1",
  "https://leetcode.com/problems/sudoku-solver/":
    "https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1",

  // ── Bit Manipulation ──────────────────────────────────────────────────────
  "https://leetcode.com/problems/number-of-1-bits/":
    "https://www.geeksforgeeks.org/problems/set-bits0143/1",
  "https://leetcode.com/problems/counting-bits/":
    "https://www.geeksforgeeks.org/problems/count-total-set-bits-1587115620/1",
  "https://leetcode.com/problems/missing-number/":
    "https://www.geeksforgeeks.org/problems/missing-number-in-array1416/1",
  "https://leetcode.com/problems/reverse-bits/":
    "https://www.geeksforgeeks.org/problems/reverse-bits-1587115620/1",
  "https://leetcode.com/problems/sum-of-two-integers/":
    "https://www.geeksforgeeks.org/problems/addition-without-plus/1",
  "https://leetcode.com/problems/single-number/":
    "https://www.geeksforgeeks.org/problems/single-number/1",
  "https://leetcode.com/problems/bitwise-and-of-numbers-range/":
    "https://www.geeksforgeeks.org/problems/bitwise-and-of-numbers-range/1",
  "https://leetcode.com/problems/powx-n/":
    "https://www.geeksforgeeks.org/problems/power-of-numbers/1",
  "https://leetcode.com/problems/factorial-trailing-zeroes/":
    "https://www.geeksforgeeks.org/problems/trailing-zeroes-in-factorial5098/1",

  // ── Greedy ────────────────────────────────────────────────────────────────
  "https://leetcode.com/problems/insert-interval/":
    "https://www.geeksforgeeks.org/problems/insert-interval/1",
  "https://leetcode.com/problems/merge-intervals/":
    "https://www.geeksforgeeks.org/problems/overlapping-intervals--170633/1",
  "https://leetcode.com/problems/non-overlapping-intervals/":
    "https://www.geeksforgeeks.org/problems/non-overlapping-intervals/1",
  "https://leetcode.com/problems/partition-labels/":
    "https://www.geeksforgeeks.org/problems/partition-labels/1",
  "https://leetcode.com/problems/gas-station/":
    "https://www.geeksforgeeks.org/problems/circular-tour-1587115620/1",
  "https://leetcode.com/problems/hand-of-straights/":
    "https://www.geeksforgeeks.org/problems/hand-of-straights/1",
  "https://leetcode.com/problems/candy/":
    "https://www.geeksforgeeks.org/problems/candy/1",
  "https://leetcode.com/problems/meeting-rooms/":
    "https://www.geeksforgeeks.org/problems/attend-all-meetings/1",
  "https://leetcode.com/problems/meeting-rooms-ii/":
    "https://www.geeksforgeeks.org/problems/attend-all-meetings/1",
  "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/":
    "https://www.geeksforgeeks.org/problems/minimum-number-of-arrows-to-burst-balloons/1",

  // ── Math / Other ──────────────────────────────────────────────────────────
  "https://leetcode.com/problems/excel-sheet-column-number/":
    "https://www.geeksforgeeks.org/problems/excel-sheet-column-number/1",
  "https://leetcode.com/problems/game-of-life/":
    "https://www.geeksforgeeks.org/problems/game-of-life/1",
  "https://leetcode.com/problems/design-twitter/":
    "https://www.geeksforgeeks.org/problems/design-twitter/1",
};
