// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// Next.js loads `.env.local` automatically, the Prisma CLI does not. Load it
// (then plain `.env`) so generate/migrate/seed work locally. On Vercel the vars
// already live in process.env, and dotenv never overrides those — a no-op there.
dotenv.config({ path: ".env.local" });
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
