/** Per-problem hints for the DSA sheets and the Top 500 bank, keyed by LeetCode
 *  slug (the segment after /problems/ in the URL). One bespoke hint per distinct
 *  problem — the recognition signal plus the key first move, never the full
 *  solution. The seed attaches HINTS[slug] to each Problem.hint; revealing a hint
 *  in the UI auto-marks "needed a hint" on the user's status.
 *
 *  516 problems covered. Keep this in sync when the problem set changes.
 */
export const HINTS: Record<string, string> = {
  "0-1-knapsack-problem0945": "Each item is take-or-leave: dp[w] = max(dp[w], value + dp[w - weight]) with the weight loop iterated downward.",
  "01-matrix": "Multi-source BFS from every 0 at once, relaxing distances outward to the 1s.",
  "132-pattern": "Scan right to left keeping a stack of candidate '3's and the max '2' popped; a current element smaller than that '2' completes a 1-3-2.",
  "3sum": "Sort, fix each i, and two-pointer the rest for pairs summing to -nums[i], skipping duplicates on all three.",
  "3sum-closest": "Sort, fix i, and move two pointers to minimise the absolute distance from the target, tracking the closest sum.",
  "4sum": "Sort and nest two fixed loops around a two-pointer inner scan, skipping duplicates and pruning on bounds.",
  "accounts-merge": "Union emails that share an account, then group emails by their root to rebuild each merged account.",
  "add-binary": "Add from the right with a carry, building the result string, then reverse.",
  "add-two-numbers": "Walk both lists adding digit by digit with a carry, creating result nodes as you go.",
  "alien-dictionary": "Derive ordering edges from the first differing character of each adjacent word pair, then topological-sort the letters (detecting cycles).",
  "all-ancestors-of-a-node-in-a-directed-acyclic-graph": "DFS/BFS from each source recording reachable descendants, or reverse-graph traversal, to collect ancestors per node.",
  "all-nodes-distance-k-in-binary-tree": "Add parent pointers (or build a graph), then BFS k steps out from the target node.",
  "all-paths-from-source-to-target": "It's a DAG: DFS from 0 accumulating the path, recording it whenever you reach n-1.",
  "assign-cookies": "Sort children and cookies, then greedily give the smallest sufficient cookie to the least greedy remaining child.",
  "asteroid-collision": "Stack of surviving asteroids; a left-moving one cancels smaller right-movers on top, is destroyed by a larger one, and both vanish on a tie.",
  "average-of-levels-in-binary-tree": "BFS level by level, averaging each level's node values.",
  "backspace-string-compare": "Scan both strings from the right, skipping characters cancelled by '#' backspaces, and compare surviving characters.",
  "balanced-binary-tree": "Post-order return each subtree's height and short-circuit to -1 the moment two children differ by more than one.",
  "baseball-game": "Push scores on a stack; '+' sums the top two, 'D' doubles the top, 'C' cancels the last, then sum the stack.",
  "basic-calculator": "Handle +, - and parentheses by pushing the running result and sign on a stack when '(' opens and restoring on ')'.",
  "basic-calculator-ii": "Scan numbers with a stack; apply * and / immediately to the top, defer + and - by pushing signed numbers, then sum.",
  "beautiful-arrangement": "Place numbers into positions one index at a time; only recurse into index i with value v when i % v == 0 or v % i == 0, and count the arrangements that fill all slots.",
  "beautiful-array": "Recursively build: odds map to 2*f(k)-1 and evens to 2*f(k), because an arithmetic-mean triple can't mix an odd and even side.",
  "best-meeting-point": "Rows and columns are independent 1-D problems; the meeting line is the median of the occupied rows and columns.",
  "best-time-to-buy-and-sell-stock": "Track the minimum price seen so far and the best profit if you sold today.",
  "best-time-to-buy-and-sell-stock-ii": "Unlimited trades: sum every positive day-to-day increase.",
  "best-time-to-buy-and-sell-stock-iii": "At most two transactions: track buy1, sell1, buy2, sell2 as four running states updated each day.",
  "best-time-to-buy-and-sell-stock-iv": "Generalise to k transactions with dp[t][hold/cash]; if k ≥ n/2 it's the unlimited-transactions greedy.",
  "best-time-to-buy-and-sell-stock-with-cooldown": "Three states per day — holding, sold (cooldown), rest; a sale forces a rest day before the next buy.",
  "best-time-to-buy-and-sell-stock-with-transaction-fee": "Two states, hold and cash; subtract the fee once per completed sell when moving hold->cash.",
  "binary-search": "Classic: keep lo/hi inclusive, compare mid to target, and shrink the half that can't contain it.",
  "binary-search-tree-iterator": "Keep a stack holding the leftmost spine; next() pops a node and pushes the left spine of its right child, giving amortised O(1) inorder.",
  "binary-tree-inorder-traversal": "Recurse left, node, right — or Morris traversal threading predecessors for O(1) space.",
  "binary-tree-level-order-traversal": "BFS processing one full queue-level at a time, emitting each level as a list.",
  "binary-tree-level-order-traversal-ii": "Do the standard level-order BFS and reverse the list of levels at the end.",
  "binary-tree-maximum-path-sum": "Post-order: each node returns the best downward arm; update a global max with node + left arm + right arm.",
  "binary-tree-paths": "DFS accumulating the path string, recording it at every leaf.",
  "binary-tree-postorder-traversal": "Recurse left, right, node — or iterate with a stack and reverse a root-right-left order.",
  "binary-tree-preorder-traversal": "Visit node then left then right, iteratively with a stack pushing right child before left.",
  "binary-tree-right-side-view": "Level-order BFS, taking the last node of each level (the rightmost).",
  "binary-tree-zigzag-level-order-traversal": "Level-order BFS but reverse the emission direction on alternate levels.",
  "bitwise-and-of-numbers-range": "The AND over a range keeps only the common high bit-prefix; strip the differing low bits by shifting both ends right until they're equal.",
  "boats-to-save-people": "Sort weights; pair the lightest with the heaviest when they fit together, otherwise ship the heaviest alone.",
  "burst-balloons": "Think of the LAST balloon to burst in a range; dp over intervals with that balloon fixed splits the range into two independent subproblems.",
  "camelcase-matching": "For each word, two-pointer against the pattern: lowercase letters may be skipped, uppercase must match in order.",
  "candy": "Two passes: give more than the left neighbour going right, then more than the right neighbour going left, taking the max at each child.",
  "candy-crush": "Repeatedly scan for horizontal/vertical runs of ≥3, zero them, drop columns by gravity, and loop until stable.",
  "capacity-to-ship-packages-within-d-days": "Binary-search the capacity between max(weight) and sum(weights); for a candidate, greedily count the days needed and keep the smallest capacity that fits in D.",
  "car-fleet": "Sort by position descending, compute each car's time to target; a car merges into the fleet ahead when its time is ≤ the fleet's, else forms a new fleet.",
  "car-pooling": "Sweep the difference array of pickups/dropoffs by location; the running passenger count must never exceed capacity.",
  "cheapest-flights-within-k-stops": "Bellman-Ford limited to k+1 relaxation rounds, or Dijkstra carrying (cost, node, stopsLeft).",
  "circular-array-loop": "Floyd's cycle detection per start, but a valid loop must keep one direction and have length > 1; mark visited zeros to prune.",
  "climbing-stairs": "It's Fibonacci: ways(n) = ways(n-1) + ways(n-2).",
  "clone-graph": "DFS/BFS copying each node once, using a visited map from original to clone to wire up neighbours.",
  "coin-change": "Unbounded knapsack for a minimum: dp[a] = 1 + min over coins of dp[a - coin], initialised to infinity.",
  "coin-change-ii": "Count combinations: loop coins on the OUTSIDE and amounts inside, so order doesn't create duplicates.",
  "combination-sum": "Numbers may repeat, so on each pick recurse from the SAME index (not i+1); subtract from the remaining target and stop when it hits 0 or goes negative.",
  "combination-sum-ii": "Duplicates in the input but each element used once: sort first, recurse from i+1, and skip a value equal to its previous sibling at the same depth to avoid duplicate combinations.",
  "combination-sum-iii": "Fixed count k and target n: recurse choosing digits 1..9 in increasing order, pruning when the running sum exceeds n or you can't reach it.",
  "combination-sum-iv": "Order matters, so it's dp[t] += dp[t - num] with the target loop outside and numbers inside.",
  "combinations": "Build k-length picks by recursing from a start index upward; prune when the remaining numbers can't fill the remaining slots.",
  "compare-version-numbers": "Split both on '.', compare revision numbers pairwise treating missing segments as 0.",
  "concatenated-words": "Sort by length and, using a trie/set of shorter words, DP each word to see if it splits into ≥2 dictionary words.",
  "constrained-subsequence-sum": "dp[i] = nums[i] + max(0, best dp in the last k); a decreasing deque supplies that windowed max in O(1).",
  "construct-binary-tree-from-inorder-and-postorder-traversal": "The last postorder value is the root; its index in inorder splits left/right subtrees, consumed right-first.",
  "construct-binary-tree-from-preorder-and-inorder-traversal": "The first preorder value is the root; locate it in inorder to size the left subtree and recurse.",
  "container-with-most-water": "Two pointers at the ends; the area is limited by the shorter wall, so move that pointer inward.",
  "contains-duplicate": "Insert into a set as you scan; a value already present means a duplicate.",
  "contains-duplicate-ii": "Map each value to its last index and check the gap, or keep a sliding window set of the last k values.",
  "contiguous-array": "Map 0 to -1 so equal 0s and 1s make the running sum repeat; the longest span between equal prefix sums is the answer.",
  "continuous-subarray-sum": "Store the first index of each prefix-sum remainder mod k; a repeated remainder ≥ 2 apart is a valid subarray.",
  "convert-sorted-array-to-binary-search-tree": "Pick the middle element as the root and recurse on the two halves to keep it height-balanced.",
  "copy-list-with-random-pointer": "Interleave each copy after its original to resolve random pointers in O(1) space, then split the two lists.",
  "corporate-flight-bookings": "Difference array: +seats at start, -seats after end, then a prefix sum reconstructs each seat total in O(n).",
  "count-and-say": "Generate each term by run-length-encoding the previous one (count then digit).",
  "count-good-nodes-in-binary-tree": "DFS carrying the max value seen on the path; a node is good when it's ≥ that max.",
  "count-number-of-nice-subarrays": "Exactly k odds = atMost(k) - atMost(k-1) using a sliding window counting odd numbers.",
  "count-of-distinct-substrings": "Insert all suffixes into a trie; the number of nodes created equals the count of distinct substrings.",
  "count-of-smaller-numbers-after-self": "Process from the right, coordinate-compress values, and query a Fenwick tree for how many smaller values you've already inserted.",
  "count-primes": "Sieve of Eratosthenes: mark multiples of each prime up to n as composite and count what's left.",
  "count-sorted-vowel-strings": "dp[i][v] counts strings of length i ending at vowel v ≥ previous; sum suffix counts, which collapses to a simple cumulative recurrence.",
  "count-square-submatrices-with-all-ones": "dp[i][j] (largest square ending here) = 1 + min of three neighbours when the cell is 1; the total of all dp values is the count.",
  "count-sub-islands": "DFS each island in grid2; it counts only if every cell of it is also land in grid1.",
  "counting-bits": "Use the recurrence bits[i] = bits[i >> 1] + (i & 1) to fill the table in O(n).",
  "couples-holding-hands": "Union adjacent seat-pairs; the minimum swaps is (couples) minus the number of union components.",
  "course-schedule": "Cycle detection on the prerequisite graph — Kahn's BFS finishing all nodes, or DFS with a recursion-stack check.",
  "course-schedule-ii": "Kahn's algorithm: repeatedly take zero-indegree courses; the order they leave the queue is a valid schedule.",
  "cousins-in-binary-tree": "BFS tracking each node's depth and parent; two values are cousins if same depth, different parents.",
  "create-sorted-array-through-instructions": "For each number, a Fenwick tree gives the count strictly less and strictly greater already inserted; add the min as the insertion cost.",
  "critical-connections-in-a-network": "Tarjan bridges: DFS tracking discovery times and low-links; an edge is a bridge when a child's low-link exceeds the parent's discovery time.",
  "daily-temperatures": "Keep a stack of indices with decreasing temperatures; a warmer day pops and resolves each waiting index's answer.",
  "decode-string": "Two stacks (counts and strings): on '[' push the multiplier and current string, on ']' pop and repeat.",
  "decode-ways": "dp[i] adds dp[i-1] when the single digit is 1-9 and dp[i-2] when the two-digit piece is 10-26.",
  "delete-and-earn": "Bucket values into counts, then it becomes house robber on the value line: taking v forbids v-1 and v+1.",
  "delete-node-in-a-bst": "Find the node; if it has two children, replace its value with the inorder successor (leftmost of the right subtree) and delete that successor.",
  "delete-the-middle-node-of-a-linked-list": "Advance slow by one and fast by two so slow lands on the middle; keep slow's predecessor to unlink it.",
  "design-add-and-search-words-data-structure": "Trie where search recurses over children on a '.' wildcard.",
  "design-browser-history": "Keep a list plus a current index; visit truncates everything after current, back/forward just clamp the index.",
  "design-circular-deque": "A fixed array with head/tail indices moving modulo capacity, plus a size counter to tell full from empty.",
  "design-circular-queue": "Ring buffer: front index and size, enqueue at (front+size)%cap, dequeue by advancing front.",
  "design-hashmap": "Use an array of buckets indexed by key % size, each bucket a small list of (key,value) pairs for collision handling.",
  "design-hashset": "Same bucketed array as a hashmap but storing keys only.",
  "design-hit-counter": "Keep timestamps in a queue (or a circular 300-second array); on getHits evict entries older than 300s.",
  "design-linked-list": "Maintain a dummy head and a size counter so index math and edge insertions/deletions share one code path.",
  "design-parking-system": "Just three counters, one per size; addCar decrements the matching counter if it's positive.",
  "design-twitter": "Store each user's tweets with a global timestamp and follow-set; getFeed merges the followed users' recent tweets with a heap.",
  "design-underground-system": "On check-in store (station, time) by id; on check-out look it up and update a (start,end) -> (totalTime, count) average table.",
  "detect-cycle-in-a-directed-graph": "DFS marking nodes white/gray/black; an edge back to a gray (in-progress) node is a cycle.",
  "detect-squares": "Count points in a hashmap; for a query point, iterate diagonal partners sharing no coordinate and multiply the counts of the other two corners.",
  "diagonal-traverse": "Walk anti-diagonals of constant i+j, reversing direction on alternate diagonals.",
  "diameter-of-binary-tree": "Post-order return each subtree's height and update a global max with left height + right height.",
  "different-ways-to-add-parentheses": "Split at each operator, recursively evaluate the left and right expressions, and combine every pair with that operator.",
  "distinct-subsequences": "dp[i][j] counts ways s[..i] forms t[..j]: always inherit dp[i-1][j], and add dp[i-1][j-1] when the characters match.",
  "divide-intervals-into-minimum-number-of-groups": "The answer is the peak overlap: sweep sorted start/end events, and the max concurrent intervals is the group count.",
  "divisor-game": "The whole game reduces to parity: the player facing an even number wins, so return n % 2 == 0.",
  "dungeon-game": "Work backwards from the princess: dp[i][j] is the min health needed entering that cell = max(1, min(right, down) - dungeon[i][j]).",
  "edit-distance": "dp[i][j] = dp[i-1][j-1] if chars match, else 1 + min(insert, delete, replace).",
  "employee-free-time": "Merge everyone's intervals into one timeline; the gaps between merged busy blocks are the common free time.",
  "encode-and-decode-strings": "Length-prefix each string (e.g. \"5#hello\") so decoding is unambiguous even when strings contain the delimiter.",
  "evaluate-division": "Model equations as a weighted graph (a/b = value) and DFS multiplying edge weights along a path between the queried variables.",
  "evaluate-reverse-polish-notation": "Push numbers; on an operator pop two operands, apply it, and push the result.",
  "excel-sheet-column-number": "Base-26 with no zero: fold each letter as result*26 + (letter - 'A' + 1).",
  "expression-add-operators": "Recurse across split points inserting +, -, or *; carry the running value and the last operand so multiplication can undo and reapply.",
  "factorial-trailing-zeroes": "Count factors of 5: n/5 + n/25 + n/125 + ...",
  "falling-squares": "Coordinate-compress the x ranges and use a segment tree with range-assign of a height and range-max query per drop.",
  "fibonacci-number": "Roll two variables forward n times instead of recursing.",
  "final-prices-with-a-special-discount-in-a-shop": "Monotonic stack of indices awaiting a discount; a price ≤ a stacked one settles it as that item's discount.",
  "find-all-anagrams-in-a-string": "Slide a fixed window the size of p, comparing letter-count arrays; record each start where they match.",
  "find-all-duplicates-in-an-array": "Values are 1..n: use each value as an index and flip that slot's sign; a slot already negative marks a duplicate.",
  "find-all-numbers-disappeared-in-an-array": "Mark index abs(v)-1 negative for each value; the positions still positive are the missing numbers.",
  "find-duplicate-subtrees": "Serialize each subtree post-order into a canonical string and collect those seen more than once.",
  "find-eventual-safe-states": "Reverse the edges and run Kahn's from terminal nodes; nodes that get fully processed are safe.",
  "find-first-and-last-position-of-element-in-sorted-array": "Run two biased binary searches — one that leans left on equality, one that leans right — to get the two boundaries.",
  "find-if-path-exists-in-graph": "Union every edge, then check the two query nodes share a root.",
  "find-k-closest-elements": "Binary-search the left end of the window of size k: compare x - a[mid] with a[mid+k] - x to decide which side is closer.",
  "find-k-pairs-with-smallest-sums": "Min-heap seeded with pairs (nums1[i], nums2[0]); pop the smallest and push its next nums2 neighbour, k times.",
  "find-largest-value-in-each-tree-row": "BFS per level, keeping the maximum value on each.",
  "find-median-from-data-stream": "Balance a max-heap of the lower half and a min-heap of the upper half; the median is a heap top or their average.",
  "find-minimum-in-rotated-sorted-array": "Compare mid with the rightmost element; if a[mid] > a[hi] the min is to the right, else it's at mid or left.",
  "find-minimum-in-rotated-sorted-array-ii": "Same as the no-duplicates version, but when a[mid] == a[hi] you can't tell sides — shrink hi by one and continue.",
  "find-peak-element": "Any local peak works: move toward the higher neighbour of mid, and you must converge on a peak.",
  "find-pivot-index": "Track the running left sum; the pivot is where left == total - left - nums[i].",
  "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance": "Run Floyd-Warshall for all-pairs distances, then pick the city with the fewest others within the threshold.",
  "find-the-duplicate-number": "Treat values as next-pointers and run Floyd's cycle detection; the cycle entrance is the duplicate.",
  "find-the-index-of-the-first-occurrence-in-a-string": "Slide the needle across the haystack, or use KMP's prefix table for O(n+m).",
  "find-the-smallest-divisor-given-a-threshold": "Binary-search the divisor from 1 to max(nums); the sum of ceil(n/divisor) decreases as the divisor grows, so find the smallest divisor keeping the sum ≤ threshold.",
  "first-bad-version": "Monotone predicate (good…good, bad…bad): binary-search for the first index where isBadVersion is true.",
  "first-missing-positive": "Place each value v in slot v-1 by swapping; the first index whose value isn't index+1 is the answer.",
  "first-unique-character-in-a-string": "Count characters in one pass, then scan again for the first with count 1.",
  "flatten-a-multilevel-doubly-linked-list": "DFS: when a node has a child, splice the flattened child list between the node and its next, fixing prev pointers.",
  "flatten-binary-tree-to-linked-list": "Reverse-preorder (right, left, node) DFS, wiring each node's right to the previously visited node and nulling left.",
  "flood-fill": "DFS/BFS from the start pixel, repainting every 4-connected neighbour of the original color.",
  "fruit-into-baskets": "Longest window with at most two distinct values — shrink from the left when a third type enters.",
  "game-of-life": "Encode next state in spare bits (e.g. bit 1) of each cell so all cells update from the original in place, then shift.",
  "gas-station": "If total gas ≥ total cost a solution exists; track the running tank and reset the start to the next station whenever it goes negative.",
  "generate-parentheses": "Track open and close counts; you may add '(' while open < n, and ')' only while close < open — that invariant keeps every prefix valid.",
  "graph-valid-tree": "A valid tree has exactly n-1 edges and no cycle — union edges and reject any that joins an already-connected pair.",
  "group-anagrams": "Key each word by its sorted letters (or its 26-count signature) and bucket words sharing a key.",
  "guess-number-higher-or-lower": "Binary-search the range 1..n, using the guess API's -1/1 result to pick which half to keep.",
  "h-index": "Sort citations descending; the h-index is the largest i where citations[i-1] ≥ i (or use counting sort).",
  "h-index-ii": "Citations are sorted; binary-search for the first index i where citations[i] >= n - i, and the h-index is n - i.",
  "hamming-distance": "XOR the two numbers, then count the set bits in the result.",
  "hand-of-straights": "Count cards, then repeatedly start a run at the smallest remaining card, consuming groupSize consecutive values or failing.",
  "happy-number": "Iterate the digit-square-sum; use fast/slow pointers to detect a cycle that isn't 1.",
  "house-robber": "dp[i] = max(skip this house dp[i-1], rob it nums[i] + dp[i-2]).",
  "house-robber-ii": "Houses form a circle, so run the linear robber twice — once excluding the first house, once excluding the last — and take the max.",
  "house-robber-iii": "Post-order returns a pair (rob this node, skip this node); a robbed node forbids robbing its children.",
  "implement-queue-using-stacks": "Two stacks — push onto 'in', and when 'out' is empty pour 'in' into it so pops come out FIFO (amortised O(1)).",
  "implement-stack-using-queues": "One queue; after each push, rotate the queue so the newest element sits at the front for LIFO pops.",
  "implement-trie-prefix-tree": "Nodes with 26 child links and an end-of-word flag support insert, search, and startsWith.",
  "insert-delete-getrandom-o1": "Pair a hashmap (value->index) with a dynamic array; delete swaps the target with the last element so removal stays O(1).",
  "insert-interval": "Copy intervals ending before the new one, merge everything overlapping it, then append the rest.",
  "insert-into-a-binary-search-tree": "Walk down comparing to each node and attach the new leaf where the search falls off the tree.",
  "insertion-sort-list": "Maintain a sorted prefix with a dummy head; for each node find its slot by walking from the dummy and splice it in.",
  "integer-break": "dp[n] = max over a cut i of max(i, dp[i]) * max(n-i, dp[n-i]); for n>4 greedily using 3s is optimal.",
  "integer-to-roman": "Greedily subtract from a descending value/symbol table that includes the subtractive pairs like 900=CM.",
  "interleaving-string": "dp[i][j] is true if s3's prefix interleaves s1[..i] and s2[..j], extending from the top or left when the matching char lines up.",
  "intersection-of-two-arrays": "Put one array in a set and collect the distinct members of the other that it contains.",
  "intersection-of-two-linked-lists": "Advance two pointers, switching each to the other list's head at its end; they meet at the join after balancing lengths.",
  "interval-list-intersections": "Two pointers: the overlap is [max(starts), min(ends)] when it's valid; advance whichever interval ends first.",
  "invert-binary-tree": "Swap each node's children and recurse.",
  "ipo": "Sort projects by capital; push all affordable projects' profits into a max-heap and repeatedly take the most profitable, up to k times.",
  "is-graph-bipartite": "BFS/DFS coloring: give each node the opposite color of its neighbour; a same-color edge means not bipartite.",
  "is-subsequence": "Advance a pointer through s only when it matches the current t character; s is a subsequence if it's fully consumed.",
  "island-perimeter": "Count each land cell as 4 sides and subtract 2 for every shared edge between adjacent land cells.",
  "isomorphic-strings": "Maintain forward and backward character maps; a consistent bijection means isomorphic.",
  "jump-game": "Track the farthest index reachable; if you ever stand beyond it you're stuck, otherwise you reach the end.",
  "jump-game-ii": "BFS-like greedy: extend the current jump's reach and increment the count when you exhaust the current level's range.",
  "jump-game-iii": "BFS/DFS from the start index, branching to i+arr[i] and i-arr[i], seeking any zero.",
  "jump-game-vi": "dp[i] = nums[i] + max dp over the previous k indices, maintained with a monotonic decreasing deque.",
  "k-closest-points-to-origin": "Keep a size-k max-heap by squared distance, evicting the farthest as you scan.",
  "keys-and-rooms": "DFS/BFS from room 0 collecting keys; you succeed if every room becomes reachable.",
  "koko-eating-bananas": "Binary-search the eating speed; for a speed, sum ceil(pile/speed) hours and keep the smallest speed that finishes within h.",
  "kth-largest-element-in-a-stream": "Hold a size-k min-heap; each add pushes then trims, and the root is the running k-th largest.",
  "kth-largest-element-in-an-array": "Maintain a size-k min-heap; its root at the end is the k-th largest (or quickselect for average O(n)).",
  "kth-smallest-element-in-a-bst": "Inorder traversal yields sorted order — stop at the k-th visited node.",
  "kth-smallest-element-in-a-sorted-matrix": "Binary-search the VALUE range (top-left..bottom-right); for a midpoint, count entries ≤ it by walking from the bottom-left in O(n).",
  "largest-divisible-subset": "Sort, then LIS-style dp where you extend a chain only when the current value is divisible by the previous, tracking predecessors to rebuild.",
  "largest-number": "Sort strings by the comparator a+b vs b+a descending, then join (guard the all-zeros case).",
  "largest-rectangle-in-histogram": "Increasing stack of bar indices; when a shorter bar arrives, pop and compute each popped bar's max rectangle width.",
  "last-stone-weight": "Max-heap: repeatedly pop the two heaviest, push back their difference, until one or none remains.",
  "last-stone-weight-ii": "Partition stones into two piles with the smallest difference — a subset-sum toward total/2.",
  "lemonade-change": "Track $5 and $10 bills; for a $20 prefer giving a $10+$5, else three $5s, failing if you can't.",
  "letter-case-permutation": "At each alphabetic character branch into lowercase and uppercase; digits pass straight through with no branch.",
  "letter-combinations-of-a-phone-number": "Map each digit to its letters and take the Cartesian product by recursing one digit deep per level.",
  "lfu-cache": "Keep per-frequency ordered lists plus a value->node map and a minFreq pointer; on access bump the node to the next frequency bucket.",
  "linked-list-cycle": "Fast moves two, slow moves one; if they ever meet there's a cycle.",
  "linked-list-cycle-ii": "After the fast/slow meeting, restart one pointer at the head and step both by one — they meet at the cycle start.",
  "longest-arithmetic-subsequence": "dp is a map per index from common-difference to chain length; extend dp[i][d] from dp[j][d] for j<i.",
  "longest-common-prefix": "Compare characters column by column across all strings, stopping at the first mismatch or shortest string.",
  "longest-common-subsequence": "dp[i][j] = dp[i-1][j-1]+1 on a match, else max(dp[i-1][j], dp[i][j-1]).",
  "longest-common-substring1452": "Like LCS but the run must be contiguous: reset dp[i][j] to 0 on a mismatch and track the running max.",
  "longest-consecutive-sequence": "Put values in a set and only start counting a run from a value with no predecessor, giving O(n).",
  "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit": "Two deques track the window's running max and min; shrink from the left while max - min exceeds the limit.",
  "longest-harmonious-subsequence": "Count values; for each v the best harmonious length is count[v] + count[v+1] when v+1 exists.",
  "longest-increasing-path-in-a-matrix": "Memoised DFS: each cell caches its longest strictly-increasing path, so the grid is a DAG explored once.",
  "longest-increasing-subsequence": "Maintain tails[] where tails[k] is the smallest tail of an LIS of length k+1, and binary-search each number's insertion point for O(n log n).",
  "longest-palindromic-subsequence": "It's LCS of the string with its reverse, or interval dp expanding matched ends inward.",
  "longest-palindromic-substring": "Expand around each of the 2n-1 centers, or interval dp on dp[i][j] = s[i]==s[j] and dp[i+1][j-1].",
  "longest-repeating-character-replacement": "Grow a window while (length - count of its most frequent char) ≤ k, shrinking otherwise.",
  "longest-string-chain": "Sort by length, then for each word try deleting each character to form a predecessor and extend that chain via a hashmap.",
  "longest-subarray-of-1s-after-deleting-one-element": "Longest window containing at most one zero, minus one for the mandatory deletion.",
  "longest-substring-with-at-most-k-distinct-characters": "Expand the window and shrink from the left whenever the distinct-count map exceeds k.",
  "longest-substring-with-at-most-two-distinct-characters": "The at-most-k window with k fixed at 2.",
  "longest-substring-without-repeating-characters": "Slide a window, and when a repeat appears jump the left edge past its last occurrence.",
  "longest-valid-parentheses": "Stack of indices with a base sentinel; on ')' pop and the gap to the new stack top is the current valid length.",
  "longest-word-in-dictionary": "Insert all words, then BFS/DFS the trie only through nodes that end a word, tracking the longest buildable word.",
  "lowest-common-ancestor-of-a-binary-search-tree": "Walk from the root: go left if both targets are smaller, right if both larger; the first split point is the LCA.",
  "lowest-common-ancestor-of-a-binary-tree": "Recurse; a node is the LCA when the two targets are found on different sides (or it is one of them).",
  "lru-cache": "Hashmap to nodes of a doubly linked list; move a node to the front on use, evict from the tail when over capacity.",
  "majority-element": "Boyer-Moore voting: keep a candidate and a count that cancels on mismatches; the survivor is the majority.",
  "majority-element-ii": "At most two elements exceed n/3: run Boyer-Moore with two candidate counters, then verify both.",
  "map-sum-pairs": "Trie storing a value at word-ends; sum queries walk to the prefix node and total the subtree's values.",
  "matchsticks-to-square": "Target side is sum/4; sort descending and try to place each stick into one of four running buckets, backtracking when a bucket overflows.",
  "matrix-chain-multiplication0303": "Interval dp: dp[i][j] is the min cost to multiply that chain, split at each k and add the outer multiply cost.",
  "max-area-of-island": "DFS each unvisited land cell summing its connected area, tracking the maximum.",
  "max-consecutive-ones": "Track the current run length of 1s and its running max.",
  "max-consecutive-ones-iii": "Longest window with at most k zeros — advance the left edge when the k-th+1 zero enters.",
  "max-sum-of-rectangle-no-larger-than-k": "Fix a column pair, compress rows to 1-D sums, then use a sorted set of prefix sums to find the best subarray ≤ k.",
  "maximal-rectangle": "Build a histogram of consecutive 1s per row and apply largest-rectangle-in-histogram to each row's heights.",
  "maximal-square": "dp[i][j] (side of the largest all-1 square ending here) = 1 + min of its top, left, and top-left neighbours when the cell is 1.",
  "maximum-average-subarray-i": "Fixed-size window sum: slide it, adding the incoming and dropping the outgoing element, tracking the max.",
  "maximum-depth-of-binary-tree": "Depth is 1 + max(left depth, right depth).",
  "maximum-frequency-stack": "Map value->count and count->stack; push updates both, pop takes from the highest-count stack which naturally breaks ties by recency.",
  "maximum-gap": "Bucket the values by range so the max gap must fall between buckets, giving O(n) instead of comparison sorting.",
  "maximum-length-of-repeated-subarray": "Contiguous LCS on two arrays: dp[i][j] = dp[i-1][j-1]+1 on equality, tracking the max.",
  "maximum-number-of-events-that-can-be-attended": "Sort by start; each day, add newly-available end times to a min-heap, drop expired ones, and attend the event ending soonest.",
  "maximum-number-of-vowels-in-a-substring-of-given-length": "Fixed window counting vowels, updated incrementally as it slides.",
  "maximum-points-you-can-obtain-from-cards": "Taking k from the ends = leaving a length n-k middle window; minimise that window's sum with a sliding window.",
  "maximum-product-subarray": "Track both the max and min product ending here — a negative flips them — and update from num, max*num, min*num.",
  "maximum-profit-in-job-scheduling": "Sort by end time; dp[i] = max(skip, profit_i + dp[last non-overlapping]) found by binary search on end times.",
  "maximum-subarray": "Kadane: extend the current run or restart at nums[i], tracking the best sum seen.",
  "maximum-subsequence-score": "Sort pairs by the second value descending; sweep keeping a size-k min-heap of the first values, and score = heap-sum * current second value.",
  "maximum-width-of-binary-tree": "BFS assigning heap-style index 2i / 2i+1 to children; each level's width is last index minus first plus one.",
  "maximum-width-ramp": "Push indices of a strictly decreasing prefix, then scan from the right popping while the stack top's value is ≤ the current to maximise the index gap.",
  "maximum-xor-of-two-numbers-in-an-array": "Binary trie of the numbers' bits; for each number greedily walk toward the opposite bit to maximise XOR.",
  "median-of-two-sorted-arrays": "Binary-search a partition of the shorter array so left halves hold the first (m+n+1)/2 elements and maxLeft ≤ minRight across both.",
  "meeting-rooms": "Sort by start and check no meeting begins before the previous one ends.",
  "meeting-rooms-ii": "Min-heap of end times: reuse a room when the earliest end is ≤ the next start, else open one; the heap size peak is the answer.",
  "merge-intervals": "Sort by start, then extend the current merged interval while the next start is ≤ the current end.",
  "merge-k-sorted-lists": "Min-heap of the current head of each list; pop the smallest, append it, and push its successor.",
  "merge-sorted-array": "Fill nums1 from the back, comparing the tails of both arrays so no element is overwritten early.",
  "merge-triplets-to-form-target-triplet": "Only use triplets that never exceed the target in any coordinate, then check those cover the target's value in each position.",
  "merge-two-sorted-lists": "Splice nodes with a dummy head, always taking the smaller current head.",
  "middle-of-the-linked-list": "Slow by one, fast by two; when fast falls off the end, slow is at the middle.",
  "min-cost-climbing-stairs": "dp[i] = cost[i] + min(dp[i-1], dp[i-2]); answer is min of the top two steps.",
  "min-cost-to-connect-all-points": "Minimum spanning tree with Prim's (or Kruskal's) over the complete graph of Manhattan distances.",
  "min-stack": "Alongside the main stack keep a second stack of running minima so getMin is O(1).",
  "minimum-absolute-difference-in-bst": "Inorder gives sorted values, so the answer is the smallest gap between consecutive visited nodes.",
  "minimum-ascii-delete-sum-for-two-strings": "LCS variant where dp adds ASCII costs of deleted characters instead of counting.",
  "minimum-cost-for-tickets": "dp over days; on a travel day take the cheapest of 1/7/30-day passes looking back the respective window.",
  "minimum-cost-to-connect-sticks": "Min-heap: always combine the two cheapest sticks and push the sum back (Huffman merging).",
  "minimum-cost-to-reach-destination-in-time": "Dijkstra over (node, timeUsed) states, minimising cost while keeping total passing time within maxTime.",
  "minimum-depth-of-binary-tree": "1 + min depth of children, but ignore a null child so a one-sided node isn't treated as a leaf.",
  "minimum-difficulty-of-a-job-schedule": "dp over (day, start index): partition the array into d contiguous groups, each contributing its max, minimising the total.",
  "minimum-falling-path-sum": "Row by row, each cell adds the min of the three cells above it.",
  "minimum-genetic-mutation": "BFS over gene strings where an edge is a single-character change to another valid gene in the bank.",
  "minimum-height-trees": "Trim leaves layer by layer; the 1 or 2 nodes remaining at the center are the roots.",
  "minimum-interval-to-include-each-query": "Sort queries and intervals; add intervals covering the query to a min-heap keyed by size, popping ones that end too early.",
  "minimum-number-of-arrows-to-burst-balloons": "Sort by end; shoot at each end point and skip all balloons it pierces — greedy interval stabbing.",
  "minimum-number-of-days-to-make-m-bouquets": "Binary-search the day; for a day, scan the bloom array counting runs of k adjacent flowers and check you get m bouquets.",
  "minimum-number-of-refueling-stops": "Drive as far as you can; when you'd run dry, greedily 'refuel' at the largest passed station using a max-heap, counting stops.",
  "minimum-operations-to-reduce-x-to-zero": "Removing from the ends to sum x = keeping a middle window summing total - x; maximise that window's length.",
  "minimum-path-sum": "dp[i][j] = grid[i][j] + min(up, left); the top row and left column only have one predecessor.",
  "minimum-platforms-1587115620": "Sort arrivals and departures separately and sweep; the maximum simultaneous trains is the platform count.",
  "minimum-remove-to-make-valid-parentheses": "Stack unmatched '(' indices and mark stray ')'; delete every unmatched parenthesis in a final pass.",
  "minimum-size-subarray-sum": "Grow the window until the sum reaches the target, then shrink from the left to find the shortest.",
  "minimum-window-subsequence": "Advance to match s2 in s1, then walk backward from the match to tighten the window start; keep the shortest.",
  "minimum-window-substring": "Expand to cover all required counts, then contract from the left while it stays valid, tracking the smallest window.",
  "missing-number": "XOR all indices 0..n with all values; the pairs cancel and the missing number remains (also solvable by sum formula).",
  "most-stones-removed-with-same-row-or-column": "Union stones sharing a row or column; the removable count is total stones minus the number of components.",
  "move-zeroes": "A write pointer collects non-zero values in order; fill the tail with zeros.",
  "multiply-strings": "Grade-school multiply: digit products land at positions i+j and i+j+1 in a result array, then carry and trim.",
  "my-calendar-i": "Keep booked intervals sorted; a new booking is allowed only if it doesn't overlap its neighbours.",
  "my-calendar-ii": "Track single-booked and double-booked intervals; reject a booking that would overlap an existing double booking.",
  "my-calendar-iii": "A sweep-line difference map (or segment tree) over booking endpoints; return the running max overlap after each add.",
  "n-meetings-in-one-room-1587115620": "Sort by finish time and greedily take each meeting that starts after the last chosen one ends.",
  "n-queens": "Go row by row; track occupied columns and both diagonals (r+c and r-c) in sets so placement checks are O(1), and backtrack on conflict.",
  "n-th-tribonacci-number": "Roll three variables forward: each term is the sum of the previous three.",
  "nearest-exit-from-entrance-in-maze": "BFS from the entrance; the first border cell (other than the entrance) you reach is the nearest exit.",
  "network-delay-time": "Dijkstra from the source; the answer is the maximum finalized distance, or -1 if any node is unreachable.",
  "next-greater-element-i": "Precompute next-greater for nums2 with a monotonic stack into a map, then answer each query from the map.",
  "next-greater-element-ii": "Circular array: run the monotonic-stack sweep over 2n indices modulo n.",
  "next-permutation": "Find the rightmost ascending pair, swap that pivot with the next-larger element to its right, then reverse the suffix.",
  "nim-game": "You lose only when the count is a multiple of 4, so return n % 4 != 0.",
  "non-overlapping-intervals": "Sort by end and keep every interval that starts after the last kept end; the rest are the minimum removals.",
  "number-of-1-bits": "Repeatedly clear the lowest set bit with n &= n-1 and count the iterations.",
  "number-of-connected-components-in-an-undirected-graph": "Union each edge and count the distinct roots that remain.",
  "number-of-enclaves": "Flood-fill land connected to the border first, then count the land cells that remain.",
  "number-of-islands": "Scan the grid; each unvisited land cell starts a DFS/BFS that sinks its whole component, incrementing the count.",
  "number-of-islands-ii": "Process each added land cell, unioning with land neighbours, and track the running component count as cells appear.",
  "number-of-longest-increasing-subsequence": "Run LIS dp but also carry a count[] of how many subsequences reach each length, combining counts on ties.",
  "number-of-operations-to-make-network-connected": "If edges ≥ n-1, the answer is components - 1 (spare cables reconnect the isolated groups).",
  "number-of-provinces": "Union directly-connected cities and count the resulting root groups.",
  "number-of-recent-calls": "Queue of timestamps; each ping enqueues now and dequeues everything older than 3000 ms, then returns the size.",
  "number-of-subarrays-with-bounded-maximum": "Count subarrays whose max ≤ R minus those ≤ L-1, each countable in one linear pass.",
  "number-of-visible-people-in-a-queue": "Right to left with a decreasing stack; each person sees the people they pop plus possibly one taller blocker.",
  "number-of-ways-to-arrive-at-destination": "Dijkstra that also carries a ways[] count, resetting on a shorter path and adding on an equal-length one, mod 1e9+7.",
  "number-of-ways-to-reorder-array-to-get-same-bst": "The first element is the root; interleave the counts from the left and right partitions using binomial coefficients, and recurse.",
  "number-of-ways-to-split-array": "Precompute the total; sweep the left prefix and count split points where left ≥ total - left.",
  "odd-even-linked-list": "Weave two chains — odd-position and even-position nodes — then link the odd tail to the even head.",
  "ones-and-zeroes": "Two-dimensional knapsack: each string costs (#zeros, #ones); dp[i][j] is the most strings fitting those two budgets.",
  "online-stock-span": "Monotonic stack of (price, span); on a new price, pop and accumulate spans of prices ≤ it.",
  "open-the-lock": "BFS over 4-digit states, each wheel ±1 per move, skipping deadends, from '0000' to the target.",
  "out-of-boundary-paths": "dp over (moves left, cell): count paths that step off the grid, summing the four neighbours' remaining-move counts, mod 1e9+7.",
  "pacific-atlantic-water-flow": "Reverse the flow: BFS/DFS inland from each ocean's border, and the answer is the cells reachable from both.",
  "palindrome-linked-list": "Find the middle with fast/slow, reverse the second half, then compare it against the first half.",
  "palindrome-number": "Reverse just the second half of the digits and compare it to the first half, avoiding overflow.",
  "palindrome-pairs": "Store reversed words in a trie/map; for each word check prefixes/suffixes whose complement forms a palindrome.",
  "palindrome-partitioning": "Cut the string at every position; recurse on the suffix only when the current prefix is a palindrome.",
  "palindrome-partitioning-ii": "Precompute an isPalindrome table, then dp[i] = min cuts for the prefix, extending from any palindromic suffix.",
  "palindromic-substrings": "Expand around each center and count every palindrome found, or use the dp[i][j] palindrome table.",
  "parallel-courses": "Kahn's algorithm counting BFS levels; the number of levels is the minimum semesters, or -1 on a cycle.",
  "partition-equal-subset-sum": "Target is total/2; boolean subset-sum dp[s] reachable by including or excluding each number.",
  "partition-labels": "Record each letter's last index; extend the current part's end to that last index and cut when the scan reaches the current end.",
  "partition-list": "Build two dummy-headed lists (less-than and ≥ x) in order, then concatenate them.",
  "partition-to-k-equal-sum-subsets": "Each subset must sum to total/k; sort descending, fill one bucket to target before opening the next, and memoise the used-mask to prune.",
  "pascals-triangle": "Each row starts and ends with 1; interior entries are the sum of the two above.",
  "path-sum": "DFS subtracting each node's value; success is a leaf where the remainder hits zero.",
  "path-sum-ii": "DFS carrying the running path and remaining target, recording the path at any leaf that zeroes it.",
  "path-sum-iii": "Carry prefix sums down the tree in a map; at each node add how many ancestor prefixes equal current - target, unwinding on return.",
  "path-with-maximum-probability": "Dijkstra with a max-heap maximising the product of edge probabilities to the destination.",
  "path-with-minimum-effort": "Dijkstra where an edge's weight is the height difference and a path's cost is its MAXIMUM edge (minimax path).",
  "peak-index-in-a-mountain-array": "Strictly increasing then decreasing — binary-search for the point where a[mid] > a[mid+1].",
  "perfect-squares": "Coin-change where the 'coins' are perfect squares ≤ n; minimise the count summing to n.",
  "permutation-in-string": "Fixed-size sliding window over s2 comparing its letter counts to s1's.",
  "permutation-sequence": "Build the k-th permutation digit by digit using factorial counts to pick each next unused digit.",
  "permutations": "Swap-in-place or use a used[] array; at each depth pick any unused element, recurse, then undo the choice.",
  "permutations-ii": "With duplicates, sort first and at each depth skip a value equal to its previous sibling when that sibling is still unused, so identical permutations aren't regenerated.",
  "plus-one": "Add one from the last digit with carry; if it ripples past the front, prepend a 1.",
  "populating-next-right-pointers-in-each-node": "Use the already-linked current level to wire the next level's pointers, giving O(1) extra space.",
  "populating-next-right-pointers-in-each-node-ii": "Walk each level via next pointers, stitching a dummy-headed chain for the level below.",
  "power-of-four": "It's a power of two (n & (n-1) == 0) whose single set bit sits in an even position (mask 0x55555555).",
  "power-of-three": "Either loop dividing by 3, or check that the largest int power of three is divisible by n.",
  "power-of-two": "Exactly one bit set: n > 0 and n & (n-1) == 0.",
  "powx-n": "Fast exponentiation: square the base and halve the exponent, multiplying in the base on odd exponents; handle negative n by inverting.",
  "predict-the-winner": "Interval dp on the score difference: dp[i][j] = max(a[i] - dp[i+1][j], a[j] - dp[i][j-1]).",
  "prefix-and-suffix-search": "Index each word by every 'suffix#prefix' key in a trie so a combined query resolves to the highest weight.",
  "product-of-array-except-self": "Two sweeps of running products — prefixes left-to-right, suffixes right-to-left — multiplied per index, no division.",
  "queries-on-a-permutation-with-key": "Place elements in a BIT sized 2n with room to move to the front; each query reads the prefix count for its current position, then moves it forward.",
  "queue-reconstruction-by-height": "Sort tallest-first, ties by fewer-in-front, then insert each person at the index equal to its k value.",
  "random-pick-with-weight": "Build a prefix-sum array of weights, roll a number in [0,total), and binary-search for the first prefix strictly greater than it.",
  "range-sum-query-2d-immutable": "Build a 2D prefix-sum grid; each rectangle sum is an inclusion-exclusion of four corner values.",
  "range-sum-query-2d-mutable": "A 2D Fenwick tree (BIT of BITs) supports point update and rectangle-sum query in O(log²).",
  "range-sum-query-immutable": "Precompute prefix sums so each query is prefix[j+1] - prefix[i].",
  "range-sum-query-mutable": "Point updates with range queries call for a Fenwick tree or segment tree over the array.",
  "ransom-note": "Tally the magazine's letters, then check the note never needs more of any letter than available.",
  "reconstruct-itinerary": "Hierholzer's Eulerian path: DFS visiting destinations in lexical order and prepend each airport as you backtrack.",
  "recover-binary-search-tree": "Inorder should be sorted; find the two out-of-order nodes (one or two adjacent inversions) and swap their values.",
  "redundant-connection": "Union edges in order; the first edge joining two already-connected nodes is the redundant one.",
  "regions-cut-by-slashes": "Split each cell into 4 triangles, union triangles across cell borders and within a cell by its slash, then count components.",
  "regular-expression-matching": "dp[i][j] matches s[..i] against p[..j]; '*' either drops the pair or, on a char/'.' match, consumes one s character.",
  "relative-sort-array": "Counting sort keyed by the order defined in arr2, appending unranked values sorted at the end.",
  "remove-all-adjacent-duplicates-in-string": "Stack characters and pop when the next equals the top, cancelling adjacent pairs.",
  "remove-all-adjacent-duplicates-in-string-ii": "Stack of (char, count); increment on a match, pop when the count hits k.",
  "remove-covered-intervals": "Sort by start ascending, end descending; count an interval as covered when its end doesn't exceed the running max end.",
  "remove-duplicate-letters": "Greedy monotonic stack: drop a larger prior letter if it appears again later, keeping each letter once and lexicographically smallest.",
  "remove-duplicates-from-sorted-array": "A slow write pointer advances only when the current value differs from the last kept one.",
  "remove-duplicates-from-sorted-array-ii": "Keep a value only if it differs from the element two slots back in the write region (allows up to two copies).",
  "remove-duplicates-from-sorted-list": "Walk the list and skip a node whose value equals the next node's.",
  "remove-duplicates-from-sorted-list-ii": "Use a dummy head; when a value repeats, advance past the entire run before relinking.",
  "remove-element": "Overwrite in place with a write pointer that skips the target value.",
  "remove-k-digits": "Monotonic increasing stack: pop a larger preceding digit while removals remain, to make the smallest number.",
  "remove-linked-list-elements": "Dummy head so removing the head is uniform; unlink each node whose value matches.",
  "remove-nth-node-from-end-of-list": "Send a lead pointer n steps ahead, then move both until it reaches the end — the trailing pointer stops before the target.",
  "reorder-list": "Split at the middle, reverse the second half, then merge the two halves alternately.",
  "reorganize-string": "Max-heap by remaining count; always place the most frequent character that isn't the one just used, else it's impossible.",
  "repeated-substring-pattern": "s is periodic iff it appears inside (s+s) with the first and last character removed.",
  "replace-words": "Build a trie of roots and, for each word, replace it with the shortest root prefix found.",
  "restore-ip-addresses": "Place three dots; each of the four segments is 1-3 digits, ≤255, and has no leading zero unless it is exactly \"0\".",
  "reveal-cards-in-increasing-order": "Simulate the reveal in reverse with a deque: sort descending, and before each insert rotate the deque's tail to the front.",
  "reverse-bits": "Pull bits off the low end of the input and push them onto the low end of the result, shifting the result left each step.",
  "reverse-integer": "Pop and push digits with mod/div, checking against INT_MIN/MAX before each push.",
  "reverse-linked-list": "Walk with prev/cur, flipping each next pointer to prev.",
  "reverse-linked-list-ii": "Reach node before position left, then repeatedly move the following node to the front of the sublist head-insertion style.",
  "reverse-nodes-in-k-group": "Check k nodes remain, reverse that block, and recurse/iterate connecting it to the reversed remainder.",
  "reverse-pairs": "Count cross pairs during a merge sort — while merging, count j where a[i] > 2*a[j] before combining the halves.",
  "reverse-string": "Swap characters from both ends moving inward.",
  "reverse-vowels-of-a-string": "Two pointers stopping on vowels from each end, swapping them.",
  "reverse-words-in-a-string": "Trim and split on whitespace, then join the words in reverse order.",
  "robot-bounded-in-circle": "After one instruction pass, the robot is bounded iff it's back at the origin or no longer facing north.",
  "robot-return-to-origin": "Count net horizontal and vertical moves; it returns iff both cancel to zero.",
  "roman-to-integer": "Scan left to right, subtracting a symbol when it's smaller than the one after it, else adding.",
  "rotate-array": "Reverse the whole array, then reverse the first k and the remaining n-k for an in-place rotation.",
  "rotate-image": "Transpose the matrix, then reverse each row, for an in-place 90° clockwise rotation.",
  "rotate-list": "Close the list into a ring, find length, then break it k % length nodes before the old tail.",
  "rotate-string": "s is a rotation of goal iff goal is a substring of s+s (and lengths match).",
  "rotting-oranges": "Multi-source BFS from all rotten oranges simultaneously; the answer is the last minute any fresh orange rots.",
  "running-sum-of-1d-array": "Overwrite each element with the sum of it and everything before it.",
  "russian-doll-envelopes": "Sort by width ascending and height descending on ties, then LIS on heights so equal widths can't nest.",
  "same-tree": "Recurse both trees in lockstep; equal iff structure and values match at every node.",
  "satisfiability-of-equality-equations": "Union all '==' variables first, then check no '!=' pair shares a root.",
  "score-of-parentheses": "Stack the running score per depth; '(' pushes 0, ')' folds the inner score as max(2*inner, 1) into the parent.",
  "search-a-2d-matrix": "Treat the row-major matrix as one sorted array of length m*n and binary-search, mapping index to (row, col).",
  "search-a-2d-matrix-ii": "Start at the top-right corner: go left when the value is too big, down when it's too small — each step eliminates a row or column.",
  "search-in-a-binary-search-tree": "Descend left or right by comparing the target to each node's value until you match or hit null.",
  "search-in-rotated-sorted-array": "One half around mid is always sorted; check whether the target lies inside that sorted half to decide which way to go.",
  "search-in-rotated-sorted-array-ii": "Same idea, but when a[lo]==a[mid]==a[hi] you can't identify the sorted half — shrink both ends by one.",
  "search-insert-position": "It's a lower-bound search: return the first index whose value is ≥ target.",
  "search-suggestions-system": "Sort products and, per typed prefix, binary-search the block and take up to three, or walk a trie collecting three leaves.",
  "seat-reservation-manager": "A min-heap of freed seats plus a next-unused counter; reserve pops the heap or hands out the counter, unreserve pushes back.",
  "sequence-reconstruction": "The sequences uniquely reconstruct org iff a topological sort has exactly one choice at every step (queue size stays 1).",
  "serialize-and-deserialize-binary-tree": "Preorder with explicit null markers serializes; deserialize by consuming that stream in the same order.",
  "set-matrix-zeroes": "Use the first row and column as zero-flags for their row/column, handling those two lines separately, for O(1) space.",
  "set-mismatch": "Cyclic-sort or sign-marking finds the index that holds a duplicate and the one left unmarked (the missing value).",
  "shortest-bridge": "DFS to find and flag the first island, then BFS outward from all its cells until you hit the second island.",
  "shortest-common-supersequence": "Build the LCS, then weave the two strings around the shared subsequence.",
  "shortest-palindrome": "Compute the longest prefix that's a palindrome via the KMP failure function of s + '#' + reverse(s), then prepend the rest reversed.",
  "shortest-path-in-binary-matrix": "BFS from top-left with 8-directional moves through 0-cells to the bottom-right.",
  "shortest-subarray-with-sum-at-least-k": "On the prefix-sum array keep an increasing deque; pop the front when a window sums ≥ k and pop the back to keep it increasing.",
  "shortest-unsorted-continuous-subarray": "The unsorted window runs from the first index below the running max (scanning left) to the last index above the running min.",
  "simplify-path": "Split on '/', push normal names, pop on '..', ignore '.' and empties, then join with '/'.",
  "single-element-in-a-sorted-array": "Pairs sit at (even, odd) indices before the single element and shift after it; binary-search on that parity to find the break.",
  "single-number": "XOR every element; equal values cancel, leaving the lone one.",
  "single-number-ii": "Every number appears three times except one; count each bit position mod 3, or track ones/twos accumulators with bit logic.",
  "single-number-iii": "XOR everything to get a^b; a lowest set bit of that splits the numbers into two groups, each XOR-ing down to one answer.",
  "single-threaded-cpu": "Sort tasks by enqueue time; a min-heap by (processing time, index) picks the next task among those already available.",
  "sliding-window-maximum": "Decreasing deque of indices; the front is the window max, and you evict indices that fall out of the window or are dominated.",
  "sliding-window-median": "Two balanced heaps like the streaming median, with lazy deletion to evict values leaving the window.",
  "smallest-range-covering-elements-from-k-lists": "Min-heap holding one element per list; the range spans heap-min to the running max, and you advance the list that owns the min.",
  "smallest-string-with-swaps": "Union swap-linked indices, then sort characters within each connected index group to get the lexicographically smallest string.",
  "snapshot-array": "Per index store a list of (snapId, value) changes; get binary-searches for the largest snapId ≤ the requested snapshot.",
  "sort-an-array": "Implement merge sort or heap sort for guaranteed O(n log n).",
  "sort-colors": "Dutch-flag three pointers: swap 0s to the front, 2s to the back, and let 1s settle in the middle in one pass.",
  "sort-items-by-groups-respecting-dependencies": "Two-level topological sort — order the groups, then items within each group, adding edges between group-representative nodes.",
  "sort-list": "Merge sort on the list: split by the slow/fast midpoint, sort each half, and merge.",
  "sort-the-matrix-diagonally": "Group cells by i-j, sort each diagonal's values, and write them back.",
  "spiral-matrix": "Maintain top/bottom/left/right bounds and peel one edge at a time, shrinking the bound after each.",
  "spiral-matrix-ii": "Same shrinking-bounds walk, but write 1..n² into the cells as you spiral inward.",
  "split-array-largest-sum": "Binary-search the answer (max subarray sum) between max(nums) and sum(nums); greedily count how many splits a candidate forces.",
  "sqrtx": "Binary-search x in [0, n] for the largest value whose square is ≤ n; guard against overflow by comparing with division.",
  "squares-of-a-sorted-array": "Merge inward from both ends since the largest squares sit at the extremes, filling the result from the back.",
  "stone-game": "Same take-from-either-end difference dp; with an even count and nonzero total the first player always wins.",
  "strange-printer": "Interval dp: dp[i][j] = dp[i][j-1] + 1, minus one whenever some k matches s[j], letting one print cover both ends.",
  "stream-of-characters": "Store the dictionary words reversed in a trie; keep recent characters and match backward from each new character.",
  "string-compression": "In place, write each character followed by its run length (omitting 1), advancing a write pointer.",
  "string-to-integer-atoi": "Skip spaces, read an optional sign, consume digits while clamping to the int range, and stop at the first non-digit.",
  "subarray-sum-equals-k": "Count prefix sums in a map; for each index add how many earlier prefixes equal current - k.",
  "subarray-sums-divisible-by-k": "Bucket prefix-sum remainders mod k (normalising negatives); C(count, 2) per bucket gives the divisible subarray count.",
  "subarrays-with-k-different-integers": "exactly(k) = atMost(k) - atMost(k-1) with a distinct-count sliding window.",
  "subsets": "For each element choose include or exclude; every leaf of that binary recursion is one subset.",
  "subsets-ii": "Sort so duplicates are adjacent, then when excluding a value skip past all its copies to avoid duplicate subsets.",
  "substring-with-concatenation-of-all-words": "Slide a window of total length using word-size steps, matching a running word-count map against the required multiset.",
  "subtree-of-another-tree": "At each node of the main tree, run a same-tree check against the candidate subtree.",
  "sudoku-solver": "Find the next empty cell, try 1-9 that don't clash in its row, column, or 3x3 box, recurse, and backtrack if the branch fails.",
  "sum-of-subarray-minimums": "For each element compute how many subarrays it's the minimum of, using previous-smaller and next-smaller spans via a monotonic stack.",
  "sum-of-two-integers": "Add without '+': XOR gives the sum without carry, AND<<1 gives the carry, loop until carry is zero.",
  "sum-root-to-leaf-numbers": "DFS building each path's number as running*10 + value, summing at the leaves.",
  "summary-ranges": "Walk the sorted array extending a run while values stay consecutive, emitting each range when it breaks.",
  "super-ugly-number": "Keep a pointer per prime into the growing sequence; each new term is the min of prime*seq[pointer], advancing tied pointers.",
  "surrounded-regions": "Mark 'O's connected to the border as safe via DFS, then flip all remaining 'O's to 'X'.",
  "swap-nodes-in-pairs": "With a dummy head, relink each adjacent pair by pointers and advance two nodes.",
  "swim-in-rising-water": "Dijkstra/min-heap where a path's cost is the maximum cell value on it — the least elevation ceiling to reach the corner.",
  "symmetric-tree": "Compare the left and right subtrees mirror-wise: outer pairs and inner pairs must match.",
  "tallest-billboard": "dp keyed by the height difference between two supports; for each rod add it to one side, the other, or skip, maximising the equal height.",
  "target-sum": "Assigning +/- to reach S means one subset sums to (total+S)/2 — a subset-count knapsack.",
  "task-scheduler": "The most frequent task sets the frame: (maxCount-1)*(n+1) + (#tasks tied for max), floored at the task count.",
  "text-justification": "Greedily pack words per line, then distribute spaces as evenly as possible (extra spaces to the left gaps); the last line is left-justified.",
  "the-skyline-problem": "Sweep the sorted edges with a max-heap of active heights; emit a key point whenever the current max height changes.",
  "time-based-key-value-store": "Store (timestamp, value) appended per key in increasing time, then binary-search for the largest timestamp ≤ the query.",
  "toeplitz-matrix": "Every cell must equal its top-left neighbour — check grid[i][j] == grid[i-1][j-1].",
  "top-k-frequent-elements": "Count frequencies, then bucket-sort by count (or a size-k heap) and take the top k.",
  "top-k-frequent-words": "Count, then a heap ordered by frequency and lexical tiebreak yields the k words.",
  "transpose-matrix": "Emit result[j][i] = matrix[i][j]; for a non-square matrix allocate n×m.",
  "trapping-rain-water": "Two pointers with running left-max and right-max; water above each bar is bounded by the smaller side.",
  "triangle": "Bottom-up: each cell becomes its value plus the min of the two cells below it.",
  "two-city-scheduling": "Send everyone to A, then pick the n people with the largest (costB - costA) savings to move to B.",
  "two-sum": "Store each value's index in a map and, per element, look up target - value.",
  "two-sum-ii-input-array-is-sorted": "Two pointers from both ends: move in on a sum too big, out on too small.",
  "two-sum-iv-input-is-a-bst": "Inorder to a sorted list then two-pointer, or DFS with a hash set of complements seen so far.",
  "ugly-number-ii": "Three pointers for factors 2, 3, 5; each next ugly number is the min of the three candidates, advancing the matching pointers.",
  "unique-binary-search-trees": "Catalan numbers: dp[n] = sum over each root choice i of dp[i-1] * dp[n-i].",
  "unique-paths": "dp[i][j] = dp[i-1][j] + dp[i][j-1] (or the binomial C(m+n-2, m-1)).",
  "unique-paths-ii": "Same additive dp but any obstacle cell contributes zero paths.",
  "valid-anagram": "Compare 26-length letter counts, or sort both strings and compare.",
  "valid-number": "Track seen digit/dot/exponent/sign flags in a single scan, or match against the numeric grammar with clear state rules.",
  "valid-palindrome": "Two pointers skipping non-alphanumerics and comparing lowercased characters from both ends.",
  "valid-palindrome-ii": "On the first mismatch, check whether skipping either the left or the right character leaves a palindrome.",
  "valid-parentheses": "Push openers and, on each closer, check it matches the top of the stack; the stack must end empty.",
  "valid-parenthesis-string": "Track a range [low, high] of possible open counts; '*' widens it, and it's valid if low reaches 0 without high going negative.",
  "valid-perfect-square": "Binary-search in [1, num] for an integer whose square equals num — no sqrt needed.",
  "valid-sudoku": "Track seen digits per row, per column, and per 3×3 box (indexed r/3*3 + c/3) with sets in one pass.",
  "validate-binary-search-tree": "Recurse carrying a (low, high) bound; every node must fall strictly inside, and each child tightens one bound.",
  "vertical-order-traversal-of-a-binary-tree": "BFS/DFS tagging each node with (column, row); sort by column, then row, then value.",
  "walking-robot-simulation": "Simulate with a direction vector, turning left/right and stepping while dodging obstacle cells stored in a set; track the max distance².",
  "walls-and-gates": "Multi-source BFS from every gate at once, filling each empty room with its distance to the nearest gate.",
  "wiggle-sort-ii": "Find the median (quickselect), then place larger-half values at odd indices and smaller-half at even indices, filling from the ends to avoid clashes.",
  "wiggle-subsequence": "Track two running lengths, up and down; each strict rise extends up from down and vice versa.",
  "wildcard-matching": "dp/greedy where '*' matches any run; remember the last '*' position to backtrack when a later mismatch occurs.",
  "word-break": "dp[i] is reachable if some j<i is reachable and s[j..i] is a dictionary word.",
  "word-break-ii": "Recurse over split points where the prefix is a dictionary word; memoise results per start index so exponential blowup is avoided.",
  "word-ladder": "BFS over words where an edge is a one-letter change; use wildcard buckets like h*t to find neighbours fast.",
  "word-ladder-ii": "BFS to build the layer graph and record predecessors, then DFS/backtrack to reconstruct all shortest paths.",
  "word-pattern": "Enforce a bijection between pattern letters and words using two maps kept consistent.",
  "word-search": "DFS from each cell matching the next letter; mark the cell visited during the branch and restore it on the way out.",
  "word-search-ii": "Build a trie of the words, then DFS the board once pruning branches that leave the trie.",
};
