export const memoryAndTheOomKill = {
  slug: "memory-and-the-oom-kill",
  title: "Memory and the OOM Kill",
  hook: "Exit code 137 at 3am, no stack trace, no error log, and a heap graph that looked healthy right up to the end. Understanding why needs virtual vs resident memory, the page cache, and what a cgroup limit actually counts.",
  tags: ["Operating Systems", "Core CS"],
  category: "CORE_CS" as const,
  minutes: 28,
  level: "Any level",
  prerequisites: "You've deployed something in a container and seen it restart.",
  afterThis: "Caching at Scale — where deliberate memory use has to be bounded on purpose.",
  suggestedFirstPass: "Start at 'Why the heap graph lied'. That's the part that makes the incident make sense.",
  references: [
    { label: "Systems Performance — Brendan Gregg" },
    { label: "Linux kernel docs — Control Group v2 memory controller" },
  ],
  body: `
## The incident

A service restarts nightly. The evidence:

- Exit code **137**
- No exception, no stack trace, nothing in the application log
- The last heap metric before death: **420MB of a 512MB max heap** — not full
- Container limit: 1GB. "So we had 500MB spare."

Three facts to reconcile: nothing crashed the process from inside, the heap wasn't full, and the container still ran out of memory. Each one points at something people usually get wrong about memory.

## Exit code 137 means it was executed, not that it failed

137 = 128 + 9. Signal 9, SIGKILL. Something outside the process killed it, and SIGKILL cannot be caught, blocked or handled — that's why there's no log line, no shutdown hook, no stack trace. Your process didn't crash; it was executed without warning.

On Linux that's almost always the **OOM killer**, and in a container it's usually the **cgroup** OOM killer enforcing the memory limit rather than the system running out. The evidence lives outside the app: \`dmesg\`, the kernel log, or \`kubectl describe pod\` showing \`OOMKilled\`. If you only look at application logs for a 137, you will find nothing and conclude "it just died."

## Virtual vs resident: which number matters

Every process sees a large **virtual** address space (VSZ). Pages only become real when touched, at which point they're **resident** (RSS) in physical RAM.

VSZ is routinely enormous and meaningless — a runtime may reserve tens of gigabytes of address space and use 200MB. **RSS is what the kernel counts against you.** Alarming on VSZ produces noise; alarming on RSS produces signal.

Two refinements worth knowing:
- **Shared pages** (the binary, shared libraries) count in each process's RSS but exist once in RAM, so summing RSS across processes double-counts. PSS (proportional set size) divides shared pages among users and is the honest per-process number.
- Memory is only allocated on **first touch**. Allocating a 1GB buffer costs nothing until you write to it — which is why a leak can look fine right up until the pages get touched.

## Why the heap graph lied

The heap is only part of what your process occupies. RSS also includes:

- **Thread stacks** — typically 1MB of virtual reservation each, and the touched part is resident. 500 threads is real memory, and thread-per-request architectures reach that number easily.
- **Native / off-heap allocations** — direct byte buffers, compression and crypto libraries, image decoders, and the driver buffers underneath your database client. Invisible to a heap profiler by definition.
- **Metaspace / code cache / JIT-compiled code** — grows with the number of loaded classes and hot methods.
- **Allocator fragmentation and retention.** This is the big one: when your runtime frees objects, the allocator usually does **not** return the pages to the OS. Freed heap is reused by the process, but RSS stays at the high-water mark. So a brief spike that the heap graph shows recovering leaves RSS permanently elevated.

That's the reconciliation: heap 420MB, plus off-heap and stacks and metaspace, plus a high-water mark that was never given back, put RSS over 1GB. The heap graph was accurate and irrelevant. **Set your container limit against RSS, not against max heap** — and leave real headroom, because heap max is a floor for your footprint, not a ceiling.

## The page cache confusion

\`free -m\` shows almost no free memory on a healthy Linux box, and this alarms people constantly. The kernel uses spare RAM as **page cache** for file data, because unused RAM is wasted RAM. That memory is instantly reclaimable — the "available" column, not "free", is the number to read.

The container-specific sting: page cache generated by *your* file I/O **counts toward your cgroup limit.** A service writing large logs or reading big files can be OOM-killed by its own cache. The kernel usually reclaims first, but under sudden pressure the killer can win the race. A steadily climbing memory graph on a service that mostly writes files is often cache, not a leak.

## Leak, pressure, or fragmentation?

Three different diseases, three different fixes, and they're distinguishable from the shape of the graph:

**Leak** — sawtooth that never returns to baseline; each cycle's trough is higher than the last. Something holds references forever: an unbounded cache, a growing listener list, a static map keyed by request. Fix: find the retention path with a heap dump.

**Pressure** — memory is proportional to concurrent work and returns to baseline when traffic drops. Nothing is leaking; the workload genuinely needs more than you gave it. Fix: bound concurrency, stream instead of buffering, or raise the limit.

**Fragmentation / high-water retention** — heap looks fine, RSS is flat and high after an early spike. Fix: cap the spike (streaming, chunking), or tune the allocator to return pages.

The single most common real cause in application code is an **unbounded cache** — a \`Map\` used as a cache with no size limit and no eviction. It's a leak with good intentions.

## Swap, OOM scores, and the container answer

Traditionally, a machine under memory pressure swaps to disk: slower, but alive. Two things change that in modern deployments — Kubernetes generally runs with swap disabled, so there's no soft-failure runway, and swapping a latency-sensitive service is often worse than restarting it. The result is a hard cliff: fine, fine, fine, SIGKILL.

The kernel picks its victim by **OOM score**, which is driven mainly by how much memory a process uses — so the biggest consumer usually dies, which is usually the process you care about most. In a container with one process, "the biggest consumer" is you.

Practical takeaways: set **requests and limits** deliberately, know that limits are enforced by the OOM killer while requests only affect scheduling, and remember that a JVM or Node process needs to be *told* about the container limit or it will size its heap against the host's memory and blow through the cgroup.

## Interview traps

1. Reading **VSZ** instead of RSS, or summing RSS across processes and double-counting shared pages.
2. **"The heap wasn't full so it can't be memory"** — ignoring off-heap, stacks, metaspace and fragmentation.
3. Not recognising **137 / SIGKILL** as an external kill, and hunting for an exception that can't exist.
4. Panicking at low "free" memory when the **page cache** is reclaimable.
5. Assuming a container OOM means the **host** is out of memory — cgroup limits are per-container.
6. Calling every rising graph a leak, without separating **leak, pressure and fragmentation**.

## The 60-second summary

> Exit 137 is SIGKILL — the process was killed from outside, almost always by the cgroup OOM killer, so there's no stack trace and the evidence is in the kernel log rather than your application log. What counts against a limit is RSS, not virtual size and not heap: thread stacks, native buffers, metaspace and allocator high-water retention all sit outside the heap graph, which is why a healthy heap can accompany an OOM kill. Page cache from your own file I/O also counts, and reclaimable cache is why "free" memory looks alarmingly low on a healthy box. Distinguish a leak (never returns to baseline, usually an unbounded cache) from pressure (proportional to load) from fragmentation (flat, high RSS after an early spike), because the fixes are entirely different. And with swap disabled there's no soft failure — you get a cliff.
`,
};
